version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Upgrading pip..."
      - pip install --upgrade pip
      - echo "Installing requirements..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Pre-build phase complete."

  build:
    commands:
      - echo "Zipping deployment artifact..."
      - zip -r build-output.zip . -x "*.git*" "*.venv*" "*__pycache__*"

artifacts:
  files:
    - '**/*'
  base-directory: .
