version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Upgrading pip..."
      - pip install --upgrade pip
      - echo "Installing build-time dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Pre-build phase: nothing to do."

  build:
    commands:
      - echo "Build phase: nothing to zip. Artifacts = raw files only."

artifacts:
  files:
    - '**/*'
  base-directory: .
