# Generated by Django 5.2 on 2025-07-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('total_payment', models.DecimalField(decimal_places=10, max_digits=20)),
                ('order_data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('track_number', models.IntegerField()),
                ('shipping_address', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
